// @generated by scripts/gen-avatar-loadout.mjs — DO NOT EDIT BY HAND
// Source: shared/avatar-loadout.json

#![allow(dead_code)]

pub const DEFAULT_PRESET_ID: &str = "wizard";
pub const BASELINE_GRANTS: &[&str] = &["drink_potion"];
pub const PRESET_IDS: &[&str] = &["paladin", "wizard"];
pub const BODY_IDS: &[&str] = &["body_f", "body_m"];
pub const ITEM_IDS: &[&str] = &["potion", "shield", "staff", "sword_1h"];
pub const GRANT_IDS: &[&str] = &["block", "cast_fireball", "cast_lightning", "drink_potion", "melee_slash"];
pub const EQUIP_SLOTS: &[&str] = &["main_hand", "off_hand"];
pub const UTILITY_SLOTS: &[&str] = &["utility_potion"];

pub fn normalize_preset_id(character_class: &str) -> Result<String, String> {
    match character_class.trim().to_ascii_lowercase().as_str() {
        "paladin" => Ok("paladin".to_string()),
        "pally" => Ok("paladin".to_string()),
        "wizard" => Ok("wizard".to_string()),
        "wizard2" => Ok("wizard".to_string()),
        _ => Err("Unsupported character class".to_string()),
    }
}

pub fn item_grants(item_id: &str) -> &'static [&'static str] {
    match item_id {
        "potion" => &["drink_potion"],
        "shield" => &["block"],
        "staff" => &["cast_fireball", "cast_lightning"],
        "sword_1h" => &["melee_slash"],
        _ => &[],
    }
}

pub fn item_slot(item_id: &str) -> Option<&'static str> {
    match item_id {
        "potion" => Some("utility_potion"),
        "shield" => Some("off_hand"),
        "staff" => Some("main_hand"),
        "sword_1h" => Some("main_hand"),
        _ => None,
    }
}

pub fn is_equip_slot(slot: &str) -> bool {
    matches!(slot, "main_hand" | "off_hand")
}

pub fn is_utility_slot(slot: &str) -> bool {
    matches!(slot, "utility_potion")
}

pub fn is_known_slot(slot: &str) -> bool {
    is_equip_slot(slot) || is_utility_slot(slot)
}

pub fn preset_grants(preset_id: &str) -> &'static [&'static str] {
    match preset_id {
        "paladin" => &["block", "drink_potion", "melee_slash"],
        "wizard" => &["cast_fireball", "cast_lightning", "drink_potion"],
        _ => &["cast_fireball", "cast_lightning", "drink_potion"],
    }
}

pub fn preset_body_id(preset_id: &str) -> &'static str {
    match preset_id {
        "paladin" => "body_m",
        "wizard" => "body_f",
        _ => "body_f",
    }
}

pub fn preset_scale(preset_id: &str) -> f32 {
    match preset_id {
        "paladin" => 1.0,
        "wizard" => 1.0,
        _ => 1.0,
    }
}

pub static PRESET_EQUIPMENT_PALADIN: &[(&str, &str)] = &[
    ("main_hand", "sword_1h"),
    ("off_hand", "shield"),
    ("utility_potion", "potion"),
];

pub static PRESET_EQUIPMENT_WIZARD: &[(&str, &str)] = &[
    ("main_hand", "staff"),
    ("utility_potion", "potion"),
];

pub fn preset_equipment_pairs(preset_id: &str) -> &'static [(&'static str, &'static str)] {
    match preset_id {
        "paladin" => PRESET_EQUIPMENT_PALADIN,
        "wizard" => PRESET_EQUIPMENT_WIZARD,
        _ => PRESET_EQUIPMENT_WIZARD,
    }
}

