/**
 * Cross-language golden-trace parity: replays `shared/fixtures/movement-trace.json`
 * (generated by the server `generate_movement_trace_fixture` test) through the
 * client `simulateMovementTick` path and asserts tick-for-tick position agreement.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import type { InputState } from '../generated/types';
import { createArenaGround } from './ground';
import {
  simulateMovementTick,
  type PlayerSimState,
} from './movement';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = path.join(
  __dirname,
  '..',
  '..',
  '..',
  'shared',
  'fixtures',
  'movement-trace.json',
);

interface TraceInput {
  forward: boolean;
  backward: boolean;
  left: boolean;
  right: boolean;
  sprint: boolean;
  jump: boolean;
}

interface TraceFrame {
  tick: number;
  input: TraceInput;
  rotationY: number;
  expected: [number, number, number];
}

interface TraceMeta {
  generatedBy: string;
  regenerate: string;
  tickRate: number;
  deltaSeconds: number;
  playerCollisionRadius: number;
  startPosition: [number, number, number];
  startRotationY: number;
}

interface MovementTrace {
  meta: TraceMeta;
  frames: TraceFrame[];
}

function loadTrace(): MovementTrace {
  const raw = readFileSync(FIXTURE_PATH, 'utf8');
  return JSON.parse(raw) as MovementTrace;
}

function toInput(frame: TraceFrame): InputState {
  return {
    forward: frame.input.forward,
    backward: frame.input.backward,
    left: frame.input.left,
    right: frame.input.right,
    sprint: frame.input.sprint,
    jump: frame.input.jump,
    sequence: 0,
    clientTick: 0,
  };
}

describe('movement golden-trace cross-language parity', () => {
  it('replays shared/fixtures/movement-trace.json within 1e-4 per axis', () => {
    const trace = loadTrace();
    expect(trace.frames.length).toBeGreaterThan(0);

    const ground = createArenaGround();
    let state: PlayerSimState = {
      position: {
        x: trace.meta.startPosition[0],
        y: trace.meta.startPosition[1],
        z: trace.meta.startPosition[2],
      },
      rotationY: trace.meta.startRotationY,
      verticalVelocity: 0,
      wasJumpPressed: false,
      sprintActive: false,
    };

    let maxAbsDivergence = 0;
    let maxAt = { tick: -1, axis: 'x', expected: 0, actual: 0 };

    for (const frame of trace.frames) {
      state = simulateMovementTick(
        state,
        toInput(frame),
        frame.rotationY,
        ground,
        trace.meta.deltaSeconds,
      );

      const axes: Array<['x' | 'y' | 'z', number, number]> = [
        ['x', state.position.x, frame.expected[0]],
        ['y', state.position.y, frame.expected[1]],
        ['z', state.position.z, frame.expected[2]],
      ];
      for (const [axis, actual, expected] of axes) {
        const abs = Math.abs(actual - expected);
        if (abs > maxAbsDivergence) {
          maxAbsDivergence = abs;
          maxAt = { tick: frame.tick, axis, expected, actual };
        }
        expect(
          abs,
          `tick ${frame.tick} ${axis}: actual=${actual} expected=${expected} |Δ|=${abs}`,
        ).toBeLessThan(1e-4);
      }
    }

    console.log(
      `[movement.trace] frames=${trace.frames.length} maxAbsDivergence=${maxAbsDivergence}`
      + ` at tick=${maxAt.tick} axis=${maxAt.axis}`
      + ` expected=${maxAt.expected} actual=${maxAt.actual}`,
    );
    expect(maxAbsDivergence).toBeLessThan(1e-4);
  });
});
