// @generated by scripts/gen-avatar-loadout.mjs — DO NOT EDIT BY HAND
// Source: shared/avatar-loadout.json

export const LOADOUT_AUTHORITY = {
  "baselineGrants": [
    "drink_potion"
  ],
  "legacyClassToPreset": {
    "paladin": "paladin",
    "pally": "paladin",
    "wizard": "wizard",
    "wizard2": "wizard"
  },
  "defaultPresetId": "wizard",
  "equipSlots": [
    "main_hand",
    "off_hand"
  ],
  "bodies": {
    "body_m": {},
    "body_f": {}
  },
  "items": {
    "sword_1h": {
      "slot": "main_hand",
      "grants": [
        "melee_slash"
      ]
    },
    "shield": {
      "slot": "off_hand",
      "grants": [
        "block"
      ]
    },
    "staff": {
      "slot": "main_hand",
      "grants": [
        "cast_fireball",
        "cast_lightning"
      ]
    },
    "potion": {
      "slot": "off_hand",
      "grants": [
        "drink_potion"
      ]
    }
  },
  "presets": {
    "paladin": {
      "label": "Paladin",
      "bodyId": "body_m",
      "scale": 1,
      "slots": {
        "main_hand": "sword_1h"
      },
      "utilityEquipment": [
        {
          "slot": "off_hand",
          "itemId": "shield"
        },
        {
          "slot": "utility_potion",
          "itemId": "potion"
        }
      ],
      "extraGrants": [
        "drink_potion"
      ]
    },
    "wizard": {
      "label": "Wizard",
      "bodyId": "body_f",
      "scale": 1,
      "slots": {
        "main_hand": "staff",
        "off_hand": "potion"
      },
      "utilityEquipment": [],
      "extraGrants": [
        "drink_potion"
      ]
    }
  }
} as const;

export const LOADOUT_DERIVED = {
  "presetIds": [
    "paladin",
    "wizard"
  ],
  "bodyIds": [
    "body_f",
    "body_m"
  ],
  "itemIds": [
    "potion",
    "shield",
    "staff",
    "sword_1h"
  ],
  "grantIds": [
    "block",
    "cast_fireball",
    "cast_lightning",
    "drink_potion",
    "melee_slash"
  ],
  "presetBodies": {
    "paladin": "body_m",
    "wizard": "body_f"
  },
  "presetGrants": {
    "paladin": [
      "block",
      "drink_potion",
      "melee_slash"
    ],
    "wizard": [
      "cast_fireball",
      "cast_lightning",
      "drink_potion"
    ]
  },
  "presetEquipmentItemIds": {
    "paladin": [
      "potion",
      "shield",
      "sword_1h"
    ],
    "wizard": [
      "potion",
      "staff"
    ]
  },
  "utilityItemsByPreset": {
    "paladin": [
      "shield",
      "potion"
    ],
    "wizard": []
  }
} as const;
