// @generated by scripts/gen-avatar-loadout.mjs — DO NOT EDIT BY HAND
// Source: shared/avatar-loadout.json
//
// String-literal unions are the compile-time face of authority ids.
// Wire/DB still carries plain strings; parse/normalize at boundaries.

export const BODY_IDS = [
  "body_f",
  "body_m",
] as const;
export type BodyId = (typeof BODY_IDS)[number];

export const ITEM_IDS = [
  "dagger",
  "potion",
  "shield",
  "sword_1h",
  "wand",
] as const;
export type ItemId = (typeof ITEM_IDS)[number];

export const ABILITY_IDS = [
  "block",
  "cast_fireball",
  "cast_lightning",
  "drink_potion",
  "melee_slash",
] as const;
/** Ability / grant id (same vocabulary as server grants). */
export type AbilityId = (typeof ABILITY_IDS)[number];

export const LOADOUT_PRESET_IDS = [
  "acolyte",
  "paladin",
  "wizard",
] as const;
export type LoadoutPresetId = (typeof LOADOUT_PRESET_IDS)[number];

export const AUTHORITY_EQUIP_SLOTS = [
  "main_hand",
  "off_hand",
] as const;
/** Exclusive paper-doll slots (at most one item per slot per player). */
export type AuthorityEquipSlot = (typeof AUTHORITY_EQUIP_SLOTS)[number];

export const AUTHORITY_UTILITY_SLOTS = [
  "utility_potion",
] as const;
/** Utility / consumable attaches (exclusive per slot id, not paper-doll). */
export type AuthorityUtilitySlot = (typeof AUTHORITY_UTILITY_SLOTS)[number];

export type AuthorityItemSlot = AuthorityEquipSlot | AuthorityUtilitySlot;

export const DEFAULT_PRESET_ID: LoadoutPresetId = "wizard";

export const LOADOUT_AUTHORITY = {
  "baselineGrants": [
    "drink_potion"
  ],
  "legacyClassToPreset": {
    "paladin": "paladin",
    "pally": "paladin",
    "wizard": "wizard",
    "wizard2": "wizard",
    "acolyte": "acolyte"
  },
  "defaultPresetId": "wizard",
  "equipSlots": [
    "main_hand",
    "off_hand"
  ],
  "utilitySlots": [
    "utility_potion"
  ],
  "bodies": {
    "body_m": {},
    "body_f": {}
  },
  "items": {
    "sword_1h": {
      "slot": "main_hand",
      "grants": [
        "melee_slash"
      ]
    },
    "shield": {
      "slot": "off_hand",
      "grants": [
        "block"
      ]
    },
    "wand": {
      "slot": "main_hand",
      "grants": [
        "cast_fireball",
        "cast_lightning"
      ]
    },
    "dagger": {
      "slot": "main_hand",
      "grants": [
        "melee_slash"
      ]
    },
    "potion": {
      "slot": "utility_potion",
      "grants": [
        "drink_potion"
      ]
    }
  },
  "presets": {
    "paladin": {
      "label": "Paladin",
      "bodyId": "body_m",
      "scale": 1,
      "slots": {
        "main_hand": "sword_1h",
        "off_hand": "shield"
      },
      "utilityEquipment": [
        {
          "slot": "utility_potion",
          "itemId": "potion"
        }
      ],
      "extraGrants": [
        "drink_potion"
      ]
    },
    "wizard": {
      "label": "Wizard",
      "bodyId": "body_f",
      "scale": 1,
      "slots": {
        "main_hand": "wand"
      },
      "utilityEquipment": [
        {
          "slot": "utility_potion",
          "itemId": "potion"
        }
      ],
      "extraGrants": [
        "drink_potion"
      ]
    },
    "acolyte": {
      "label": "Acolyte",
      "bodyId": "body_f",
      "scale": 1,
      "slots": {
        "main_hand": "wand"
      },
      "utilityEquipment": [
        {
          "slot": "utility_potion",
          "itemId": "potion"
        }
      ],
      "extraGrants": [
        "drink_potion"
      ]
    }
  }
} as const;

export const LOADOUT_DERIVED = {
  "presetIds": [
    "acolyte",
    "paladin",
    "wizard"
  ],
  "bodyIds": [
    "body_f",
    "body_m"
  ],
  "itemIds": [
    "dagger",
    "potion",
    "shield",
    "sword_1h",
    "wand"
  ],
  "grantIds": [
    "block",
    "cast_fireball",
    "cast_lightning",
    "drink_potion",
    "melee_slash"
  ],
  "equipSlots": [
    "main_hand",
    "off_hand"
  ],
  "utilitySlots": [
    "utility_potion"
  ],
  "presetBodies": {
    "acolyte": "body_f",
    "paladin": "body_m",
    "wizard": "body_f"
  },
  "presetGrants": {
    "acolyte": [
      "cast_fireball",
      "cast_lightning",
      "drink_potion"
    ],
    "paladin": [
      "block",
      "drink_potion",
      "melee_slash"
    ],
    "wizard": [
      "cast_fireball",
      "cast_lightning",
      "drink_potion"
    ]
  },
  "presetEquipmentItemIds": {
    "acolyte": [
      "potion",
      "wand"
    ],
    "paladin": [
      "potion",
      "shield",
      "sword_1h"
    ],
    "wizard": [
      "potion",
      "wand"
    ]
  },
  "utilityItemsByPreset": {
    "acolyte": [
      "potion"
    ],
    "paladin": [
      "potion"
    ],
    "wizard": [
      "potion"
    ]
  }
} as const;

/** Runtime guard when a string arrives from the network / DB. */
export function isBodyId(value: string): value is BodyId {
  return (BODY_IDS as readonly string[]).includes(value);
}
export function isItemId(value: string): value is ItemId {
  return (ITEM_IDS as readonly string[]).includes(value);
}
export function isAbilityId(value: string): value is AbilityId {
  return (ABILITY_IDS as readonly string[]).includes(value);
}
export function isLoadoutPresetId(value: string): value is LoadoutPresetId {
  return (LOADOUT_PRESET_IDS as readonly string[]).includes(value);
}
export function isAuthorityEquipSlot(value: string): value is AuthorityEquipSlot {
  return (AUTHORITY_EQUIP_SLOTS as readonly string[]).includes(value);
}
export function isAuthorityUtilitySlot(value: string): value is AuthorityUtilitySlot {
  return (AUTHORITY_UTILITY_SLOTS as readonly string[]).includes(value);
}
export function isAuthorityItemSlot(value: string): value is AuthorityItemSlot {
  return isAuthorityEquipSlot(value) || isAuthorityUtilitySlot(value);
}
